services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      TZ: Asia/Kolkata
#    networks:
#      - app-network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
#    networks:
#      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak-themes:/opt/keycloak/themes
    command:
      - start-dev
      - --db=dev-file
      - --spi-theme--static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
#    networks:
#      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
#    networks:
#      - app-network

volumes:
  keycloak-data:
    driver: local

#networks:
#  app-network:
#    driver: bridge
